### ISSUE TITLE
[BUG] Snake - Snake can disappear

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#10]
**Describe the bug**

When the player travels to the top or bottom of the game area, they can press the left or right keys and the snake will disappear. It will not reappear at the other end of the game area. It continues moving out of sight until the player changes direction again or a loss occurs. I did not notice this issue with the sides of the game area, only top and bottom.

**To Reproduce**
1. Go to ['...'](https://wortal.digitalwill.co.jp/games/snake/40/)
2. Move to the top or bottom of the game area
3. Change directions as soon as the snake reaches the blue square marking the end of the game area.

**Expected behavior**

Snake should not disappear.

**Screenshots**
![snake-missing](https://user-images.githubusercontent.com/26350151/144534574-79683c64-1a36-4844-be2d-6536aa5d472c.jpg)

**Comment by GroovyWilliam** [comment]
Fix issue in [d814229d1be6dbf23e6a3e7c72df6488dd86da91](https://github.com/Digital-Will-Inc/html5-games/commit/d814229d1be6dbf23e6a3e7c72df6488dd86da91)

**Comment by trdillon** [comment]
This is resolved in the latest revision.
