### ISSUE TITLE
[BUG] Nail - Game freezes after ad

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#12]
**Describe the bug**

After ad is displayed the game does not regain focus. On desktop clicking the game canvas again will trigger a restart, but on mobile tapping the screen does not restart the game. The player has to change to a different tab or screen then return to trigger a restart.

**Expected behavior**

Game restart should trigger immediately after ad is shown.

**Comment by GroovyWilliam** [comment]
Fix issue in (7e503f794a4f2ea549bc62651333f85572a2da97)[https://github.com/Digital-Will-Inc/html5-games/commit/7e503f794a4f2ea549bc62651333f85572a2da97]
