### ISSUE TITLE
[BUG] Circle Path - Game freezes after ad

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#13]
**Describe the bug**

After ad is displayed the game does not regain focus. On desktop clicking the game canvas again will trigger a restart, but on mobile tapping the screen does not restart the game. The player has to change to a different tab or screen then return to trigger a restart.

**Expected behavior**

Game restart should trigger immediately after ad is shown.

**Comment by GroovyWilliam** [comment]
Issue is already fix wasn't upload to Wortal production.
[Game](https://html5gameportal.com/developers/2/games/34/32d73056-b9a5-4f64-b817-484f8d34cf1e/) has been updated to wortal.
