### ISSUE TITLE
[BUG] Circle Path - Japanese font not displaying

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#14]
**Describe the bug**

Japanese font is not displaying correctly.

**Expected behavior**

Japanese font displays properly.

**Screenshots**

![font](https://user-images.githubusercontent.com/26350151/144540190-c805fe48-0027-452b-babb-d7065ccaad24.jpg)

**Comment by GroovyWilliam** [comment]
Issue was already fixed but not uploaded to Wortal production.
Have fixed the issue now in the [game](https://html5gameportal.com/developers/2/games/34/32d73056-b9a5-4f64-b817-484f8d34cf1e/)
