### ISSUE TITLE
[I18N] HexGL - In-game text missing localization

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#16]
Some in-game text is missing localization.

![ingame_translation](https://user-images.githubusercontent.com/26350151/144542784-da2cd2c1-88f9-4f70-981f-d6dc0b57f1a6.jpg)

**Comment by HDZD** [comment]
Fixing the tutorial controls would require translating the help .png tutorial images found under 

HexGL/Build/css/help-*.png

I will update the translation sheet with the required strings and send it back to shoji, then we can have someone from art edit the images
