### ISSUE TITLE
[BUG] Tower Blocks - Japanese font is not displaying

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#17]
**Describe the bug**

Japanese font is not displaying correctly.

**Expected behavior**

Japanese font displays properly.

**Screenshots**

![japanese-font](https://user-images.githubusercontent.com/26350151/144546113-703f709a-e35c-4b69-aa74-52c44b32502e.jpg)

**Comment by GroovyWilliam** [comment]
Fix issue in [0aea7ce3950b7b07d17eae512f09663f29e93f2c](https://github.com/Digital-Will-Inc/html5-games/commit/0aea7ce3950b7b07d17eae512f09663f29e93f2c)
