### ISSUE TITLE
[BUG] Flip - Japanese font is not displaying

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#19]
**Describe the bug**

Japanese font is not displaying correctly.

**Expected behavior**

Japanese font displays properly.

**Screenshots**

![japanese-font](https://user-images.githubusercontent.com/26350151/144546900-25cea702-ac0b-4f8b-86d8-006cc4377f74.jpg)

**Comment by GroovyWilliam** [comment]
Fixed issue in [ab122a148aa40f0d5294868f0a5ba62a79b114d0](https://github.com/Digital-Will-Inc/html5-games/commit/ab122a148aa40f0d5294868f0a5ba62a79b114d0)
