### ISSUE TITLE
[BUG] Color Match - Japanese text overflow

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#20]
**Describe the bug**

When the player loses a game on mobile (portrait) the Japanese text overflows, making it difficult to read.

**Expected behavior**

Text stays within the game area, as it does in English.

**Screenshots**

![japanese_overflow](https://user-images.githubusercontent.com/26350151/144548381-ce1929ae-ef53-43e4-9c01-c5edc2502b85.jpg)

**Comment by GroovyWilliam** [comment]
Fix issue in [3d830d101b087056c660e1a9f980108de530d2e7](https://github.com/Digital-Will-Inc/html5-games/commit/3d830d101b087056c660e1a9f980108de530d2e7)

**Comment by trdillon** [comment]
It appears this issue still exists on mobile
![text-overflow2](https://user-images.githubusercontent.com/26350151/144775502-8fdbfd31-eba6-4b99-b723-d23919a93bfc.jpg)
.

**Comment by GroovyWilliam** [comment]
Game was updated in Wortal-Dev
But have uploaded the [game](https://html5gameportal.com/developers/2/games/26/f74eeace-9637-4ba0-bd2e-a5dd6bcae112/) it now to Wortal-Prod
