### ISSUE TITLE
[BUG] Emoji Minesweeper - Canvas overflows onto website header

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#21]
**Describe the bug**

In mobile browsers the canvas overflows into the website header.

**Expected behavior**

The website header is not visible.

**Screenshots**

![canvas-overflow](https://user-images.githubusercontent.com/26350151/144549369-03c2efe4-2840-4918-ab5a-010ef591c6da.jpg)

**Comment by GroovyWilliam** [comment]
Fix issue in [ba32ad5a2230d4dfe0da2b30db9af572d915c680](https://github.com/Digital-Will-Inc/html5-games/commit/ba32ad5a2230d4dfe0da2b30db9af572d915c680)
