### ISSUE TITLE
[BUG] Align 4 - Canvas not sized properly

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#22]
**Describe the bug**

On desktop the canvas is too large and causes scroll bars to appear. On mobile the canvas is not sized for portrait or landscape. The game is marked as any orientation, so it should be properly sized for portrait and landscape, otherwise the orientation setting should be changed accordingly.

**Expected behavior**

Canvas fits into the screen space neatly.

**Screenshots**

![canvas-size](https://user-images.githubusercontent.com/26350151/144550150-61a6f434-7489-4b7a-8d5d-b8b55da7d880.jpg)
![canvas-portrait](https://user-images.githubusercontent.com/26350151/144550155-ae4b26a8-9e54-4b5d-b62b-7a7353c49ef3.jpg)
![canvas-landscape](https://user-images.githubusercontent.com/26350151/144550159-e1a6d82f-d4be-470c-a210-b6d9d2f983e6.jpg)

**Comment by GroovyWilliam** [comment]
Fix issue in [99c832e6201bd9d5ca4ca6c9bb703cf5aac0580d](https://github.com/Digital-Will-Inc/html5-games/commit/99c832e6201bd9d5ca4ca6c9bb703cf5aac0580d)
