### ISSUE TITLE
[BUG] Coil - Console log is being flooded with info logs

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#3]
**Describe the bug**

Game is flooding the console log with the same message repeatedly.

**To Reproduce**
1. Go to ['...'](https://wortal.digitalwill.co.jp/games/coil/39/)
2. Open dev console
3. Play

**Expected behavior**

Game should not flood console with info

**Screenshots**

![consoleflood](https://user-images.githubusercontent.com/26350151/144229436-685adf7a-b2b6-4cda-9f00-4864fce69e36.jpg)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by HDZD** [comment]
Fixed in d25326c465b2f76af67ec5d3160beea66ba141b8
