### ISSUE TITLE
[BUG] Snake - Canvas is cropped

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#4]
**Describe the bug**

Canvas is cropped at the bottom so the player cannot see the entire map. Issue only appears on desktop, mobile canvas is fine.

**To Reproduce**
1. Go to ['...'](https://wortal.digitalwill.co.jp/games/snake/40/)
2. Play
3. See error

**Expected behavior**

Whole canvas is shown.

**Screenshots**

![canvas-cropped](https://user-images.githubusercontent.com/26350151/144230383-76a077e8-938d-4890-bccf-a98a01b35655.jpg)

**Desktop (please complete the following information):**
 - Browser: Firefox

**Comment by GroovyWilliam** [comment]
Fix the issue in `246a447c4db242f01e9e67c4e858ba56f30be5bf`
