### ISSUE TITLE
[BUG] Snake - Moving downward on mobile can cause refresh

### ISSUE THREAD

**Issue by trdillon** [Digital-Will-Inc/html5-games#5]
**Describe the bug**

Not so much a bug as a design challenge.. if the player swipes down to change direction it's usually fine, but if they hold the swipe down even slightly, it will cause the browser to refresh and restart the game. 

This can be an accessibility issue for older people or people with some physical impairments.

**To Reproduce**
1. Go to ['...'](https://wortal.digitalwill.co.jp/games/snake/40/)
2. Play
3. Swipe down but hold a fraction of a second

**Expected behavior**

Game doesn't refresh when changing directions.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy
 - OS: Android
 - Browser: Chrome

**Additional context**

This might be a tricky one to resolve, and it's more of an edge case/accessibility issue than a critical bug. Not sure if we can really do anything about this, but it's something to consider if we can.

**Comment by GroovyWilliam** [comment]
Fix this in  [34e6ff42a40d953d2bef9c55e53d546ff716d504](https://github.com/Digital-Will-Inc/html5-games/commit/34e6ff42a40d953d2bef9c55e53d546ff716d504)

Made sure that 'touchmove' inputs inside canvas won't allow refresh effect to happen
